# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: redcarpet
title: Manyu Gou

redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
        title: 小勾の胡言乱语

description: 小勾の胡言乱语
author:
  name: XiaoGo
  email: me@myg0u.com
  github: wswuai
# twitter: wswuai
# pinterest: wswuai
# linkedin: wswuai
  bio:  Hey, I'm Geek.
  email_md5: 11111111111111

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about_me.html

gems : [ jekyll-paginate ]
BASE_PATH : 
